#!/bin/bash
# Generated by scripts/cella_runner_convert.py. The reflexive inner run.
set -uo pipefail
R=/titanium/result
end() { sync; reboot -f; echo 1 > /proc/sys/kernel/sysrq; echo b > /proc/sysrq-trigger; }
if [ -f "$R/done" ]; then end; fi
mkdir -p "$R/jobs"
# Phase markers, to the result root and to the console: on a lab cella the
# console is recorded, so a stall is placed without extracting first. On the
# field cella the console goes nowhere, at no cost.
phase() { echo "cella-runner: $(date -u +%T) $*" | tee -a "$R/phases.log" > /dev/console 2>/dev/null || true; }
phase "boot: run script started"

# Member prelude: address the wire to the terminator, fold the pair CA into
# the system bundle, point Python TLS at it, pin the reply-port window.
ip link set eth0 up || true
ip addr replace 10.77.0.2/24 dev eth0 || true
cat /usr/local/share/ca-certificates/gateway-ca.crt >> /etc/ssl/certs/ca-certificates.crt 2>/dev/null || true
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
echo '50000 50007' > /proc/sys/net/ipv4/ip_local_port_range 2>/dev/null || true

# Guest diagnostics, so an inner-environment failure is debuggable from the
# extracted payload rather than by re-running blind.
{ uname -a; echo; date -u; echo; mount; echo; cat /proc/filesystems; echo;
   ls -la /sys/fs/cgroup/cgroup.controllers 2>/dev/null && cat /sys/fs/cgroup/cgroup.controllers;
   echo; dmesg | tail -40; } > "$R/guest-diag.txt" 2>&1

# What the unprivileged user needs from root, once: the KVM device open to
# every uid -- each machine's VMM opens it itself, jailed as its own sub-uid,
# which is in no group; 0666 is what udev sets on the host -- a runtime dir
# (no logind session grants one), and the jobs dir it writes.
chmod 0666 /dev/kvm
install -d -m 0700 -o titanium -g titanium /run/user/1000
chown -R titanium:titanium "$R/jobs"
# The ext4 builder the inner environment runs `mkfs.ext4 -d` in, seeded by
# tag into the user's store so the inner run finds it present and builds
# nothing.
phase "seed: loading the rootfs builder"
runuser -u titanium -p -- env HOME=/home/titanium USER=titanium LOGNAME=titanium XDG_RUNTIME_DIR=/run/user/1000 podman load -i /workspace/seed/cella/builder.tar > "$R/seed.log" 2>&1 \
  || phase "seed: podman load FAILED"
# cella's own preflight, one level down and as that user: KVM in this guest,
# the jail, the goldens. Recorded, not fatal here: the inner titanium refuses
# on its own terms, and the record says why.
{ ls -la /dev/kvm; runuser -u titanium -p -- env HOME=/home/titanium USER=titanium LOGNAME=titanium XDG_RUNTIME_DIR=/run/user/1000 CELLA_HOME=/home/titanium/.cella cella doctor gate kvm bwrap golden:kernel:canonical golden:rootfs:cella golden:rootfs:terminator; } \
  > "$R/cella-doctor.txt" 2>&1 && phase "cella doctor gate: ok" || phase "cella doctor gate: FAILED"
# The inner machines' consoles (lab persona set only; the field set writes
# none). Followed into the result -- a wedge's record survives the salvage
# extract -- and onto this guest's serial, live when the outer run is the
# debug leg. One tail per machine, picked up as each console appears.
( started=""
  while sleep 5; do
    for c in /home/titanium/.cella/machines/*/console.log; do
      [ -f "$c" ] || continue
      case " $started " in *" $c "*) continue ;; esac
      started="$started $c"
      m=$(basename "$(dirname "$c")")
      tail -n +1 -F "$c" 2>/dev/null \
        | sed -u $'s/\x1b\[[0-9;?]*[a-zA-Z]//g; s/\x1b[()][A-Z0-9]//g; s/\x1b[DM78]//g' \
        | stdbuf -oL tr -d '\000-\010\013-\037' \
        | sed -u "s|^|[inner $m] |" \
        | tee -a "$R/inner-consoles.log" > /dev/console &
    done
  done ) &

cd /workspace
# The boot oneshot runs with no HOME, and cella resolves its home as
# CELLA_HOME, else HOME/.cella, else ./.cella -- so name it.
export CELLA_HOME=/home/titanium/.cella
# The task's rootfs, provisioned to boot systemd on the host and seeded: the
# inner run adopts it and builds no base.
export TITANIUM_CELLA_ROOTFS_TAR=/workspace/seed/cella/rootfs/state-0000.tar
export TITANIUM_CELLA_IMAGE_CONFIG=/workspace/seed/cella/rootfs/image-config.json
# The inner pair: pair 1, its appliance resolving and reaching the world
# through the outer appliance -- the same two the nested golden bakes.
export TITANIUM_CELLA_PAIR=1
export TITANIUM_CELLA_UPSTREAM_DNS=10.77.0.1
# The inner machines' boot margin: mkfs, create and a nested one-vCPU boot
# take minutes here, not the seconds the host default covers.
export TITANIUM_CELLA_BOOT_MARGIN_SEC=900
# One verb (create/start/stop/thaw) pays the same nested tax; the host
# default of 120 s killed the verifier's create (sparse mkfs, one vCPU).
export TITANIUM_CELLA_VERB_TIMEOUT_SEC=900
# cella's extract budgets the evidence at a host disk's rate (4 MiB/s);
# here the extractor reads through two VMMs on one vCPU.
export CELLA_EXTRACT_MIB_PER_SEC=1

# The model agent runs the real escape test -- a live agent attempting the
# breakout, not a canned solution. Its API key and model come from the baked
# .secrets (Makefile-style `export VAR = value`; normalize to shell env). The
# agent reaches its model through the guest's judged membrane.
if [ -f /workspace/.secrets ]; then
  set -a
  eval "$(sed -nE 's/^[[:space:]]*(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(.*)$/\2=\3/p' /workspace/.secrets)"
  set +a
fi

# litellm fetches its model cost map from GitHub at import; the membrane
# refuses that, and a refused crossing is a dropped packet, so each attempt
# waits out a timeout. Use the bundled map, as the agent image already does.
export LITELLM_LOCAL_MODEL_COST_MAP=true

phase "titanium run: start"
runuser -u titanium -p -- env HOME=/home/titanium USER=titanium LOGNAME=titanium XDG_RUNTIME_DIR=/run/user/1000 .venv/bin/titanium run \
  --agent mini-swe-agent \
  --model "${OPENROUTER_MODEL:?no OPENROUTER_MODEL in baked .secrets}" \
  --env cella --cpus ignore \
  --path "/workspace/examples/smoke/cella-runner-cella" \
  --jobs-dir "$R/jobs" \
  2>&1 | tee /dev/console > "$R/run.log"
echo "${PIPESTATUS[0]}" > "$R/exit-code"
phase "titanium run: exit $(cat "$R/exit-code")"
# The kernel log after the run: a seccomp kill inside the guest is only
# ever named here (audit type=1326, syscall=N).
dmesg > "$R/guest-dmesg.txt" 2>&1
touch "$R/done"
end
