#!/bin/bash
# Generated by scripts/cella_runner_convert.py. The reflexive inner run.
set -uo pipefail
R=/titanium/result
end() { sync; reboot -f; echo 1 > /proc/sys/kernel/sysrq; echo b > /proc/sysrq-trigger; }
if [ -f "$R/done" ]; then end; fi
mkdir -p "$R/jobs"
# Phase markers, to the result root and to the console: on a lab cella the
# console is recorded, so a stall is placed without extracting first. On the
# field cella the console goes nowhere, at no cost.
phase() { echo "cella-runner: $(date -u +%T) $*" | tee -a "$R/phases.log" > /dev/console 2>/dev/null || true; }
phase "boot: run script started"

# Member prelude: address the wire to the terminator, fold the pair CA into
# the system bundle, point Python TLS at it, pin the reply-port window.
ip link set eth0 up || true
ip addr replace 10.77.0.2/24 dev eth0 || true
cat /usr/local/share/ca-certificates/gateway-ca.crt >> /etc/ssl/certs/ca-certificates.crt 2>/dev/null || true
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
echo '50000 50007' > /proc/sys/net/ipv4/ip_local_port_range 2>/dev/null || true

# Guest diagnostics, so an inner-environment failure is debuggable from the
# extracted payload rather than by re-running blind.
{ uname -a; echo; date -u; echo; mount; echo; cat /proc/filesystems; echo;
   ls -la /sys/fs/cgroup/cgroup.controllers 2>/dev/null && cat /sys/fs/cgroup/cgroup.controllers;
   echo; dmesg | tail -40; } > "$R/guest-diag.txt" 2>&1

# The daemon the inner `--env docker` run drives. This script owns its
# lifecycle rather than a systemd `Requires=`, so its log is always captured
# under the result root and a failure is visible in the extracted payload
# instead of vanishing into a dependency-failed unit. Clear any stale pid a
# prior boot left, then start it. Retry once: a first-boot flake (e.g. a
# boltdb open racing a slow tmpfs mount) should not sink the whole run.
# Container egress leaves the guest through the wire nic. Docker masquerades
# every compose network with its own iptables-nft rule (priority srcnat), which
# keeps the container's source port -- outside the reply window the appliance
# grants. A connection is source-NATed once, by the first nat chain that binds
# it, so this chain at priority srcnat-1 wins: every flow out of the wire nic
# is masqueraded into the reply window the member prelude pinned for the guest
# itself, and the appliance's answers are named by a granted port.
echo 1 > /proc/sys/net/ipv4/ip_forward
nft -f - <<NFT || echo "could not install the reply-window masquerade" >> "$R/dockerd.log"
table ip cellarun {
  chain post {
    type nat hook postrouting priority srcnat - 1; policy accept;
    oifname "eth0" ip protocol tcp masquerade to :50000-50007
    oifname "eth0" ip protocol udp masquerade to :50000-50007
  }
}
NFT
phase "masquerade: $(nft list chain ip cellarun post 2>/dev/null | grep -c masquerade) rules"
start_dockerd() {
  rm -f /var/run/docker.pid
  dockerd >> "$R/dockerd.log" 2>&1 &
  DPID=$!
  for _ in $(seq 1 90); do
    docker info >/dev/null 2>&1 && return 0
    kill -0 "$DPID" 2>/dev/null || return 1
    sleep 1
  done
  return 1
}
if ! start_dockerd; then
  echo "dockerd did not come up; retrying once" >> "$R/dockerd.log"
  pkill dockerd 2>/dev/null; sleep 2; rm -f /var/run/docker.pid
  start_dockerd || true
fi
docker info > "$R/docker-info.txt" 2>&1 \
  && phase "dockerd ready" \
  || { echo "dockerd never became ready" >> "$R/dockerd.log"; phase "dockerd NOT ready"; }

# Import the baked base images (docker export -> tar -> docker import), so the
# inner build finds them locally and needs no pull. Airgapped by design.
if [ -f /workspace/seed/load.sh ]; then
  phase "seed: importing images"
  bash /workspace/seed/load.sh > "$R/seed.log" 2>&1
  phase "seed: done ($(docker images -q | wc -l) images)"
fi

cd /workspace
# The egress sidecar was built on the host and seeded (load.sh above).
export TITANIUM_EGRESS_PROXY_IMAGE=titanium-egress-proxy:cella-runner
# The task+agent image, built on the host and seeded: the inner run builds nothing.
export TITANIUM_AGENT_IMAGE=titanium-agent:cella-runner
# Use the seeded image as-is when it was prebuilt on the host: the guest is
# airgapped and cannot run the Dockerfile's network build steps (apt, clone).
# built in-guest from the seeded base

# The model agent runs the real escape test -- a live agent attempting the
# breakout, not a canned solution. Its API key and model come from the baked
# .secrets (Makefile-style `export VAR = value`; normalize to shell env). The
# agent reaches its model through the guest's judged membrane.
if [ -f /workspace/.secrets ]; then
  set -a
  eval "$(sed -nE 's/^[[:space:]]*(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=[[:space:]]*(.*)$/\2=\3/p' /workspace/.secrets)"
  set +a
fi

# litellm fetches its model cost map from GitHub at import; the membrane
# refuses that, and a refused crossing is a dropped packet, so each attempt
# waits out a timeout. Use the bundled map, as the agent image already does.
export LITELLM_LOCAL_MODEL_COST_MAP=true

phase "titanium run: start"
 .venv/bin/titanium run \
  --agent mini-swe-agent \
  --model "${OPENROUTER_MODEL:?no OPENROUTER_MODEL in baked .secrets}" \
  --env docker --cpus ignore --memory ignore \
  --path "/workspace/examples/smoke/cella-runner-docker" \
  --jobs-dir "$R/jobs" \
  2>&1 | tee /dev/console > "$R/run.log"
echo "${PIPESTATUS[0]}" > "$R/exit-code"
phase "titanium run: exit $(cat "$R/exit-code")"
# The kernel log after the run: a seccomp kill inside the guest is only
# ever named here (audit type=1326, syscall=N).
dmesg > "$R/guest-dmesg.txt" 2>&1
touch "$R/done"
end
